/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import "RCTRootView.h"
#import "../Libraries/LinkingIOS/RCTLinkingManager.h"
#import "RCTPushNotificationManager.h"
#import "AppLogin.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [self toRootView:launchOptions];
  //return YES;
  [FBSDKProfile enableUpdatesOnAccessTokenChange:YES];
//  [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(profileUpdated:) name:FBSDKProfileDidChangeNotification object:nil];
  
  return [[FBSDKApplicationDelegate sharedInstance] application:application
                                  didFinishLaunchingWithOptions:launchOptions];
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  if ([sourceApplication isEqualToString:@"com.tencent.xin"]) {
    return [RCTLinkingManager application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
  }
  else
  {
    return [[FBSDKApplicationDelegate sharedInstance] application:application
                                                          openURL:url
                                                sourceApplication:sourceApplication
                                                       annotation:annotation];
  }
  
}

- (void)applicationDidEnterBackground:(UIApplication *)application
{
  NSLog(@"=== DID ENTER BACKGROUND ===");
  UIBackgroundTaskIdentifier bgTask = [[UIApplication  sharedApplication] beginBackgroundTaskWithExpirationHandler:^{
    NSLog(@"End of tolerate time. Application should be suspended now if we do not ask more 'tolerance'");
  }];
  
  if (bgTask == UIBackgroundTaskInvalid) {
    NSLog(@"This application does not support background mode");
  }
  else {
    //if application supports background mode, we'll see this log.
    NSLog(@"Application will continue to run in background");
  }
}

// Required to register for notifications
- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings
{
  [RCTPushNotificationManager didRegisterUserNotificationSettings:notificationSettings];
}
// Required for the register event.
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  [RCTPushNotificationManager didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}
// Required for the notification event.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification
{
  [RCTPushNotificationManager didReceiveRemoteNotification:notification];
}
// Required for the localNotification event.
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
{
  [RCTPushNotificationManager didReceiveLocalNotification:notification];
}

-(void)toRootView:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;
  
  /**
   * Loading JavaScript code - uncomment the one you want.
   *
   * OPTION 1
   * Load from development server. Start the server from the repository root:
   *
   * $ npm start
   *
   * To run on device, change `localhost` to the IP address of your computer
   * (you can get this by typing `ifconfig` into the terminal and selecting the
   * `inet` value under `en0:`) and make sure your computer and iOS device are
   * on the same Wi-Fi network.
   */
  
  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
  
  /**
   * OPTION 2
   * Load from pre-bundled file on disk. The static bundle is automatically
   * generated by "Bundle React Native code and images" build step.
   */
  
//  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"Webuzz"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
//  NSLog([[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) lastObject] stringByAppendingString:@"/"]);
}

-(void)profileUpdated:(NSNotification *) notification{
//  NSLog(@"User name: %@",[FBSDKProfile currentProfile].name);
//  NSLog(@"User ID: %@",[FBSDKProfile currentProfile].userID);
//  NSLog(@"Link URL: %@",[FBSDKProfile currentProfile].linkURL);
//  NSLog(@"Refresh Date: %@",[FBSDKProfile currentProfile].refreshDate);
  AppLogin * al= [[AppLogin alloc] init];
  
  if ([FBSDKProfile currentProfile] == nil) {
    [al logout];
    return;
  }
  
  NSMutableDictionary* parameters = [NSMutableDictionary dictionary];
  [parameters setValue:@"id,name,context,picture{url},locale,gender" forKey:@"fields"];
  
  [[[FBSDKGraphRequest alloc] initWithGraphPath:@"me" parameters:parameters]
   startWithCompletionHandler:^(FBSDKGraphRequestConnection *connection,
                                id result, NSError *error) {
     
     if (result && !error && ![al isLogin])
     {
       NSMutableDictionary * mdic =  [[NSMutableDictionary alloc] init];
       NSDictionary *  dic =  result;
       
       NSMutableDictionary * facebookDic = [[NSMutableDictionary alloc]init];
       [facebookDic setObject:[dic objectForKey:@"id"] forKey:@"id"];
       [facebookDic setObject:[[[dic objectForKey:@"picture"] objectForKey:@"data"] objectForKey:@"url"] forKey:@"headimgurl"];
       [facebookDic setObject:[dic objectForKey:@"name"] forKey:@"name"];
       
       
       if(![al checkIfUserIDExist:[dic objectForKey:@"id"] loginType:@"facebook" loginInfo:facebookDic])
       {
         if(![al checkIfUserLinkInfo:facebookDic withSource:@"facebook"]){
           
//         [mdic setObject:[dic objectForKey:@"id"] forKey:@"userid"];
//         [mdic setObject:[dic objectForKey:@"name"] forKey:@"name"];
////       [mdic setObject:[dic objectForKey:@"context"] forKey:@"unionid"];
//         [mdic setObject:[[[dic objectForKey:@"picture"] objectForKey:@"data"] objectForKey:@"url"] forKey:@"headimgurl"];
//         [mdic setObject:[dic objectForKey:@"locale"] forKey:@"city"];
//         [mdic setObject:[dic objectForKey:@"gender"] forKey:@"sex"];
       
           NSDictionary * loginInfoDic = [[NSDictionary alloc]init];
         
         
           NSMutableDictionary * facebookDic = [[NSMutableDictionary alloc]init];
           [facebookDic setObject:[dic objectForKey:@"id"] forKey:@"id"];
           [facebookDic setObject:[[[dic objectForKey:@"picture"] objectForKey:@"data"] objectForKey:@"url"] forKey:@"headimgurl"];
           [facebookDic setObject:[dic objectForKey:@"name"] forKey:@"name"];
           
           NSString *gender =[dic objectForKey:@"gender"];
           
          loginInfoDic = [al getUserInfoWithEmail:@""
                           nickname:[dic objectForKey:@"name"]
                          firstname:@""
                           lastname:@""
                             gender:[gender substringWithRange:NSMakeRange(0, 1)]
                             wechat:nil
                           facebook:facebookDic];
         
           [al saveAndPostUserInfo:loginInfoDic withSource:@"facebook"];
         }
       }
     }
     else
     {
       [al logout];
     }
     [self toRootView:nil];
   }];
  
  //AppLogin * ap = [[AppLogin alloc] init];
  //[al onFaceBookLoginFinish];

}

@end
